//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_T_REC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees_Position
    {
        public string Emp_id { get; set; }
        public int Pos_id { get; set; }
        public decimal cost { get; set; }
    }
}
