//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_T_REC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Equip_type_id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string Fullname { get; set; }
        public string SN { get; set; }
        public string Number { get; set; }
        public Nullable<decimal> CostBuy { get; set; }
        public Nullable<decimal> CostRent { get; set; }
        public string SupplierName { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public string ReceiptTax { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    }
}
