//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_T_REC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_SET_detail
    {
        public int SET_ID { get; set; }
        public int Equip_ID { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> discount { get; set; }
        public int running { get; set; }
    }
}
