//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_T_REC.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Employees> Employees { get; set; }
        public DbSet<Employees_Position> Employees_Position { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<Equipment_SET> Equipment_SET { get; set; }
        public DbSet<Equipment_SET_detail> Equipment_SET_detail { get; set; }
        public DbSet<Equipment_Type> Equipment_Type { get; set; }
        public DbSet<JobPosition> JobPosition { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<JobPosition_Emp> JobPosition_Emp { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
