//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_T_REC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Equip
    {
        public Package_Equip()
        {
            this.Packages = new HashSet<Packages>();
        }
    
        public int Pack_Equip_Id { get; set; }
        public Nullable<int> Equip_Id { get; set; }
    
        public virtual ICollection<Packages> Packages { get; set; }
    }
}
