//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_T_REC.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Set
    {
        public Package_Set()
        {
            this.Packages = new HashSet<Packages>();
        }
    
        public int Pack_Set_ID { get; set; }
        public Nullable<int> SET_ID { get; set; }
    
        public virtual Equipment_SET Equipment_SET { get; set; }
        public virtual ICollection<Packages> Packages { get; set; }
    }
}
